// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanningInfoSystemAPI.Data;

#nullable disable

namespace PlanningInfoSystemAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240125142905_Ninth")]
    partial class Ninth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanningInfoSystemAPI.DowntimeGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DowntimeGuide");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlanningRequest");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine1Tbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualHours")
                        .HasColumnType("int");

                    b.Property<int?>("ChangeOver")
                        .HasColumnType("int");

                    b.Property<string>("DelayStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DieSizeThickness")
                        .HasColumnType("int");

                    b.Property<string>("DowntimeGuide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EffectiveCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MT")
                        .HasColumnType("int");

                    b.Property<int>("PlanningId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeProduce")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningId");

                    b.ToTable("PlanningRequestLine1Tbl");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine2Tbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualHours")
                        .HasColumnType("int");

                    b.Property<int?>("ChangeOver")
                        .HasColumnType("int");

                    b.Property<string>("DelayStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DieSizeThickness")
                        .HasColumnType("int");

                    b.Property<string>("DowntimeGuide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EffectiveCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MT")
                        .HasColumnType("int");

                    b.Property<int>("PlanningId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeProduce")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningId");

                    b.ToTable("PlanningRequestLine2Tbl");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine3Tbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualHours")
                        .HasColumnType("int");

                    b.Property<int?>("ChangeOver")
                        .HasColumnType("int");

                    b.Property<string>("DelayStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DieSizeThickness")
                        .HasColumnType("int");

                    b.Property<string>("DowntimeGuide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EffectiveCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MT")
                        .HasColumnType("int");

                    b.Property<int>("PlanningId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeProduce")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningId");

                    b.ToTable("PlanningRequestLine3Tbl");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.ProductClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductClassifications");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine1Tbl", b =>
                {
                    b.HasOne("PlanningInfoSystemAPI.Models.PlanningRequest", "Planning")
                        .WithMany("Line1")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine2Tbl", b =>
                {
                    b.HasOne("PlanningInfoSystemAPI.Models.PlanningRequest", "Planning")
                        .WithMany("Line2")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequestLine3Tbl", b =>
                {
                    b.HasOne("PlanningInfoSystemAPI.Models.PlanningRequest", "Planning")
                        .WithMany("Line3")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("PlanningInfoSystemAPI.Models.PlanningRequest", b =>
                {
                    b.Navigation("Line1");

                    b.Navigation("Line2");

                    b.Navigation("Line3");
                });
#pragma warning restore 612, 618
        }
    }
}
